# Generated by Django 2.1.5 on 2019-06-24 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('major', models.CharField(max_length=15)),
                ('enter_year', models.IntegerField()),
                ('image', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('Content', models.TextField()),
                ('Image', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='enter_term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enter_term', to='alumni.Term'),
        ),
        migrations.AddField(
            model_name='member',
            name='portfolio',
            field=models.ManyToManyField(blank=True, to='alumni.Port'),
        ),
        migrations.AddField(
            model_name='member',
            name='tutor',
            field=models.ManyToManyField(related_name='tutor', to='alumni.Term'),
        ),
    ]
