# Generated by Django 2.1.5 on 2019-06-09 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='Portfolio',
            new_name='portfolio',
        ),
    ]
