# Generated by Django 2.1.5 on 2019-06-24 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='tutor',
            field=models.ManyToManyField(blank=True, related_name='tutor', to='alumni.Term'),
        ),
    ]
