# Generated by Django 2.1.5 on 2019-06-24 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0002_auto_20190624_1810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='port',
            old_name='Content',
            new_name='content',
        ),
    ]
