# Generated by Django 2.1.5 on 2019-06-24 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0003_auto_20190624_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='portfolio',
            field=models.ManyToManyField(blank=True, related_name='member', to='alumni.Port'),
        ),
    ]
