# Generated by Django 2.1.5 on 2019-06-24 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0004_auto_20190624_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='enter_term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enter_members', to='alumni.Term'),
        ),
        migrations.AlterField(
            model_name='member',
            name='portfolio',
            field=models.ManyToManyField(blank=True, related_name='port_members', to='alumni.Port'),
        ),
        migrations.AlterField(
            model_name='member',
            name='tutor',
            field=models.ManyToManyField(blank=True, related_name='tutors', to='alumni.Term'),
        ),
    ]
